version: '1.0'
name: pipeline-20220325
displayName: pipeline-20220325
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-2a91a068
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: hub.docker.com
        username: liujin0506
        password: lj4569119
        tag: liujin0506/zencode:${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        isCache: true
  - name: stage-45d69245
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
permissions:
  - role: admin
    members: []
